=head1 Self Wiki

=head2 L<存储|../storage/index.html>

当前的工作，-_-b

=head2 L<Perl语言|../perl/index.html>

做事麻利，不多说

=head2 L<Emacs编辑器|../emacs/index.html>

一本万利

=head2 L<Debian操作系统|../debian/index.html>

这是自由的思想在传播

=head2 L<Common Lisp语言|../lisp/index.html>

没有数据结构，这是精髓

=head2 L<游戏攻略|../game/index.html>

玩游戏的，都是和平主义者