=head1 游戏攻略

=head2 炉石传说

=over

=item 专注于单个角色（法师）

=item 初期参考别人已经成熟的攻略

=item 把握比赛的节奏（按前期，中期，后期），进行出牌

=item 这是场仆从间的较量（自己的仆从尽量多，对方的仆从尽量少）

=back

=head2 如何做事？

=over

=item 目的：想要达到的目标。目的改变了，其他也要相应改变；目的消失了，其他也无必要了。

=item 设计：预先规划，制定图样。测试目的是否合理；设定实施步骤和范围。

=item 实施：实际施行。在设计的框架内逐步达到目标。

=item 工具：工作时所用的器具。更有效地尝试各种设计；更有效的实施。

=back

=head2 创始人

=over

=item 产品：尽早发布，迭代式开发

=item 市场：和用户之间没有其他人（初期：用户但求精不求多）

=item 团队：寻找优秀的人才

=item 方向：面向未来（密切关注公司的发展）

=item 处事：冷静，坚韧，主次分明（对当前任务有贯彻的执行力）

=item 性格：工作务实，行动迅速

=item 基础：找个起点作为支撑，向前开拓

=item 勇气：在陌生的领域需要勇气进行决断，但要记住这里的危险，在最短的时间找到方法降低这个危险

=back

=head2 合伙人

=over

=item 处得来

=item 技能互补

=item 趣味相投

=item 坚韧不拔

=back

=head2 面向未来

=over

=item 工作：没有铁饭碗

=item 教育：紧跟变化，守住不变

=item 行业：消亡加剧，支柱产业长期缓慢发展

=item 投资：依循生活方式的转变和国家的政策调控

=item 生活：以预见的眼光审视未来，寻找当前与未来的接洽点

=item 其他：社会化发展模式将成为主流，封闭式发展将萎缩或者消亡

=back

=head2 并行

=over

=item 将独立事件分开处理

=item 将复合事件分解为独立事件

=back