=head1 游戏攻略

=head2 警告

这只是个游戏，没什么大不了

=head2 好游戏的标准

=over

=item 激发创造力

=item 具有挑战性

=item 自由和空间

=item 简单和统一

=item 够得着的胜利

=back

=head2 游戏的多面性

=over

=item 设计者看到的那面

=item 使用者看到的那面

=back

=head2 炉石传说

=over

=item 专注于某个角色

=item 参考别人已经成熟的攻略

=item 按比赛节奏进行出牌

=item 仆从是比赛的主体

=back

=head2 如何做事？

=over

=item 目的：想要达到的目标。目的改变了，其他也要相应改变；目的消失了，其他也无必要了。

=item 设计：预先规划，制定图样。测试目的是否合理；设定实施步骤和范围。

=item 实施：实际施行。在设计的框架内逐步达到目标。

=item 工具：工作时所用的器具。更有效地尝试各种设计；更有效的实施。

=item 方法：

=over

=item 读万卷书

=item 行万里路

=item 名家指路

=back

=back

=head2 做事方法

=over

=item 每天最多做三件事

=item 以结果为导向衡量工作进度

=item 养成良好的生活习惯

=back

=head2 创始人

=over

=item 产品：尽早发布，迭代式开发

=item 市场：和用户之间没有其他人（初期：用户但求精不求多）

=item 团队：寻找优秀的人才

=item 方向：面向未来（密切关注公司的发展）

=item 处事：冷静，坚韧，主次分明（对当前任务有贯彻的执行力）

=item 性格：工作务实，行动迅速

=item 基础：找个起点作为支撑，向前开拓

=item 勇气：在陌生的领域需要勇气进行决断，但要记住这里的危险，在最短的时间找到方法降低这个危险

=back

=head2 合伙人

=over

=item 处得来

=item 技能互补

=item 趣味相投

=item 坚韧不拔

=back

=head2 团队

=over

=item 先建好队伍，再分配任务

=item 保持团队成员在一起工作

=item 模式化工作，而不依靠个人

=item 建立短而规律的出货周期

=back

=head2 时间

=over

=item 树立一个目标

=item 把握住灵感

=item 明确工作进度

=item 利用“玩”的时间

=back

=head2 展示与讨论

ppt只能用于展示；技术并不能带来新思想；讨论需要互动和好奇心

=head2 面向未来

=over

=item 工作：没有铁饭碗

=item 教育：紧跟变化，守住不变

=item 行业：消亡加剧，支柱产业长期缓慢发展

=item 投资：依循生活方式的转变和国家的政策调控

=item 生活：以预见的眼光审视未来，寻找当前与未来的接洽点

=item 其他：社会化发展模式将成为主流，封闭式发展将萎缩或者消亡

=back

=head2 并行

=over

=item 将独立事件分开处理

=item 将复合事件分解为独立事件

=item 加速必须是由需求引起

=item 代码锁简单但容易引起锁竞争

=item 数据锁通过分散降低了锁竞争，但热门条目仍存在激烈竞争

=back

=head2 翻墙

这是一种长期的艺术行为

=head2 投资游戏

=over

=item 银行定期存储利率：4.75%

=item 余额宝利率：4.0% ~ 6.0%

=item 银行理财产品：5.0% ~ 6.0%

=item 基金：用于选择投资方向

=item 股票：选定三个行业进行实际操作（新能源汽车，医疗器械服务，核能概念）

=back

=head2 简单开发原则

=over

=item 将所有材料尽可能集中在一起

=over

=item 需求分析

=item 程序设计

包括功能设计和交换界面设计

=item 软件测试

=item 软件部署

=item 软件维护

=back

=item 将需求、设计和实现放置在一起

多显示器或者简单开发原则

=item 用最熟悉的方式对问题和方案进行描述

=item 线上是线下的延续

=item 函数多并不代表易维护

函数 + 说明 = 易维护

=item 想一下，如果XX有某项功能就好了

=back