=head1 Debian

=head2 tmpwatch

Linux使用tmpwatch命令和cron守护进程来定期清理临时目录。

当有文件消失不见而原因未知时，可能是由它引起的。

=head2 字体

英文环境 + infinality补丁包，显示效果非常棒！

=head2 命令行设置代理

export http_proxy=http://127.0.0.1:8087

=head2 发送信号量

kill用于向进程发送信号量；若信号量为0,则不发送任何信号量，用于检查进程是否存在。

=head2 性能监控工具

=over

=item 用户活动： psacct, acct

=item 进程监控：top, htop, monit

=item 进程带宽：nethogs

=item 网络带宽：iftop

=item 网络包：tcpdump

=item 网络状态：netstat

=item 以太网活动：arpwatch

=item 网络安全：suricata

=item 网络流量：vnstat

=item 局域网IP：iptraf

=item 打开的文件：lsof

=item 磁盘I/O：iotop

=item 输入/输出：iostat

=item 虚拟内存：vmstat

=item 网络/服务器：monitorix, nagios

=back

=head2 开发工具

=over

=item C语言：NetBeans

=item 网页：Brackets

=back

=head2 测试

这是多级列表测试

=over

=item C语言家族

=over

=item C

=item C++

=item C#

=back

=item perl语言家族

=over

=item perl 5

当前版本 5.18.2

=item perl 6

没有尝试过

=back

=item lisp语言家族

lisp有很多方言

=over

=item lisp-1

函数与变量使用统一命名空间

=item lisp-2

函数和变量使用不同命名空间

=back

=back